<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * FIT 21.171 SDK
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * BenchPressExerciseName constants
 */
final class BenchPressExerciseName
{
    const ALTERNATING_DUMBBELL_CHEST_PRESS_ON_SWISS_BALL = 0;
    const BARBELL_BENCH_PRESS = 1;
    const BARBELL_BOARD_BENCH_PRESS = 2;
    const BARBELL_FLOOR_PRESS = 3;
    const CLOSE_GRIP_BARBELL_BENCH_PRESS = 4;
    const DECLINE_DUMBBELL_BENCH_PRESS = 5;
    const DUMBBELL_BENCH_PRESS = 6;
    const DUMBBELL_FLOOR_PRESS = 7;
    const INCLINE_BARBELL_BENCH_PRESS = 8;
    const INCLINE_DUMBBELL_BENCH_PRESS = 9;
    const INCLINE_SMITH_MACHINE_BENCH_PRESS = 10;
    const ISOMETRIC_BARBELL_BENCH_PRESS = 11;
    const KETTLEBELL_CHEST_PRESS = 12;
    const NEUTRAL_GRIP_DUMBBELL_BENCH_PRESS = 13;
    const NEUTRAL_GRIP_DUMBBELL_INCLINE_BENCH_PRESS = 14;
    const ONE_ARM_FLOOR_PRESS = 15;
    const WEIGHTED_ONE_ARM_FLOOR_PRESS = 16;
    const PARTIAL_LOCKOUT = 17;
    const REVERSE_GRIP_BARBELL_BENCH_PRESS = 18;
    const REVERSE_GRIP_INCLINE_BENCH_PRESS = 19;
    const SINGLE_ARM_CABLE_CHEST_PRESS = 20;
    const SINGLE_ARM_DUMBBELL_BENCH_PRESS = 21;
    const SMITH_MACHINE_BENCH_PRESS = 22;
    const SWISS_BALL_DUMBBELL_CHEST_PRESS = 23;
    const TRIPLE_STOP_BARBELL_BENCH_PRESS = 24;
    const WIDE_GRIP_BARBELL_BENCH_PRESS = 25;
    const ALTERNATING_DUMBBELL_CHEST_PRESS = 26;
}
