<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * FIT 21.141 SDK
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * CrunchExerciseName constants
 */
final class CrunchExerciseName
{
    const BICYCLE_CRUNCH = 0;
    const CABLE_CRUNCH = 1;
    const CIRCULAR_ARM_CRUNCH = 2;
    const CROSSED_ARMS_CRUNCH = 3;
    const WEIGHTED_CROSSED_ARMS_CRUNCH = 4;
    const CROSS_LEG_REVERSE_CRUNCH = 5;
    const WEIGHTED_CROSS_LEG_REVERSE_CRUNCH = 6;
    const CRUNCH_CHOP = 7;
    const WEIGHTED_CRUNCH_CHOP = 8;
    const DOUBLE_CRUNCH = 9;
    const WEIGHTED_DOUBLE_CRUNCH = 10;
    const ELBOW_TO_KNEE_CRUNCH = 11;
    const WEIGHTED_ELBOW_TO_KNEE_CRUNCH = 12;
    const FLUTTER_KICKS = 13;
    const WEIGHTED_FLUTTER_KICKS = 14;
    const FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH = 15;
    const WEIGHTED_FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH = 16;
    const FOAM_ROLLER_REVERSE_CRUNCH_WITH_DUMBBELL = 17;
    const FOAM_ROLLER_REVERSE_CRUNCH_WITH_MEDICINE_BALL = 18;
    const FROG_PRESS = 19;
    const HANGING_KNEE_RAISE_OBLIQUE_CRUNCH = 20;
    const WEIGHTED_HANGING_KNEE_RAISE_OBLIQUE_CRUNCH = 21;
    const HIP_CROSSOVER = 22;
    const WEIGHTED_HIP_CROSSOVER = 23;
    const HOLLOW_ROCK = 24;
    const WEIGHTED_HOLLOW_ROCK = 25;
    const INCLINE_REVERSE_CRUNCH = 26;
    const WEIGHTED_INCLINE_REVERSE_CRUNCH = 27;
    const KNEELING_CABLE_CRUNCH = 28;
    const KNEELING_CROSS_CRUNCH = 29;
    const WEIGHTED_KNEELING_CROSS_CRUNCH = 30;
    const KNEELING_OBLIQUE_CABLE_CRUNCH = 31;
    const KNEES_TO_ELBOW = 32;
    const LEG_EXTENSIONS = 33;
    const WEIGHTED_LEG_EXTENSIONS = 34;
    const LEG_LEVERS = 35;
    const MCGILL_CURL_UP = 36;
    const WEIGHTED_MCGILL_CURL_UP = 37;
    const MODIFIED_PILATES_ROLL_UP_WITH_BALL = 38;
    const WEIGHTED_MODIFIED_PILATES_ROLL_UP_WITH_BALL = 39;
    const PILATES_CRUNCH = 40;
    const WEIGHTED_PILATES_CRUNCH = 41;
    const PILATES_ROLL_UP_WITH_BALL = 42;
    const WEIGHTED_PILATES_ROLL_UP_WITH_BALL = 43;
    const RAISED_LEGS_CRUNCH = 44;
    const WEIGHTED_RAISED_LEGS_CRUNCH = 45;
    const REVERSE_CRUNCH = 46;
    const WEIGHTED_REVERSE_CRUNCH = 47;
    const REVERSE_CRUNCH_ON_A_BENCH = 48;
    const WEIGHTED_REVERSE_CRUNCH_ON_A_BENCH = 49;
    const REVERSE_CURL_AND_LIFT = 50;
    const WEIGHTED_REVERSE_CURL_AND_LIFT = 51;
    const ROTATIONAL_LIFT = 52;
    const WEIGHTED_ROTATIONAL_LIFT = 53;
    const SEATED_ALTERNATING_REVERSE_CRUNCH = 54;
    const WEIGHTED_SEATED_ALTERNATING_REVERSE_CRUNCH = 55;
    const SEATED_LEG_U = 56;
    const WEIGHTED_SEATED_LEG_U = 57;
    const SIDE_TO_SIDE_CRUNCH_AND_WEAVE = 58;
    const WEIGHTED_SIDE_TO_SIDE_CRUNCH_AND_WEAVE = 59;
    const SINGLE_LEG_REVERSE_CRUNCH = 60;
    const WEIGHTED_SINGLE_LEG_REVERSE_CRUNCH = 61;
    const SKATER_CRUNCH_CROSS = 62;
    const WEIGHTED_SKATER_CRUNCH_CROSS = 63;
    const STANDING_CABLE_CRUNCH = 64;
    const STANDING_SIDE_CRUNCH = 65;
    const STEP_CLIMB = 66;
    const WEIGHTED_STEP_CLIMB = 67;
    const SWISS_BALL_CRUNCH = 68;
    const SWISS_BALL_REVERSE_CRUNCH = 69;
    const WEIGHTED_SWISS_BALL_REVERSE_CRUNCH = 70;
    const SWISS_BALL_RUSSIAN_TWIST = 71;
    const WEIGHTED_SWISS_BALL_RUSSIAN_TWIST = 72;
    const SWISS_BALL_SIDE_CRUNCH = 73;
    const WEIGHTED_SWISS_BALL_SIDE_CRUNCH = 74;
    const THORACIC_CRUNCHES_ON_FOAM_ROLLER = 75;
    const WEIGHTED_THORACIC_CRUNCHES_ON_FOAM_ROLLER = 76;
    const TRICEPS_CRUNCH = 77;
    const WEIGHTED_BICYCLE_CRUNCH = 78;
    const WEIGHTED_CRUNCH = 79;
    const WEIGHTED_SWISS_BALL_CRUNCH = 80;
    const TOES_TO_BAR = 81;
    const WEIGHTED_TOES_TO_BAR = 82;
    const CRUNCH = 83;
    const STRAIGHT_LEG_CRUNCH_WITH_BALL = 84;
}
