<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * Profile Version = 21.54Release
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * HipRaiseExerciseName constants
 */
final class HipRaiseExerciseName
{
    const BARBELL_HIP_THRUST_ON_FLOOR = 0;
    const BARBELL_HIP_THRUST_WITH_BENCH = 1;
    const BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE = 2;
    const WEIGHTED_BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE = 3;
    const BRIDGE_WITH_LEG_EXTENSION = 4;
    const WEIGHTED_BRIDGE_WITH_LEG_EXTENSION = 5;
    const CLAM_BRIDGE = 6;
    const FRONT_KICK_TABLETOP = 7;
    const WEIGHTED_FRONT_KICK_TABLETOP = 8;
    const HIP_EXTENSION_AND_CROSS = 9;
    const WEIGHTED_HIP_EXTENSION_AND_CROSS = 10;
    const HIP_RAISE = 11;
    const WEIGHTED_HIP_RAISE = 12;
    const HIP_RAISE_WITH_FEET_ON_SWISS_BALL = 13;
    const WEIGHTED_HIP_RAISE_WITH_FEET_ON_SWISS_BALL = 14;
    const HIP_RAISE_WITH_HEAD_ON_BOSU_BALL = 15;
    const WEIGHTED_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL = 16;
    const HIP_RAISE_WITH_HEAD_ON_SWISS_BALL = 17;
    const WEIGHTED_HIP_RAISE_WITH_HEAD_ON_SWISS_BALL = 18;
    const HIP_RAISE_WITH_KNEE_SQUEEZE = 19;
    const WEIGHTED_HIP_RAISE_WITH_KNEE_SQUEEZE = 20;
    const INCLINE_REAR_LEG_EXTENSION = 21;
    const WEIGHTED_INCLINE_REAR_LEG_EXTENSION = 22;
    const KETTLEBELL_SWING = 23;
    const MARCHING_HIP_RAISE = 24;
    const WEIGHTED_MARCHING_HIP_RAISE = 25;
    const MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL = 26;
    const WEIGHTED_MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL = 27;
    const REVERSE_HIP_RAISE = 28;
    const WEIGHTED_REVERSE_HIP_RAISE = 29;
    const SINGLE_LEG_HIP_RAISE = 30;
    const WEIGHTED_SINGLE_LEG_HIP_RAISE = 31;
    const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH = 32;
    const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BENCH = 33;
    const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL = 34;
    const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_BOSU_BALL = 35;
    const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER = 36;
    const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_FOAM_ROLLER = 37;
    const SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL = 38;
    const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_FOOT_ON_MEDICINE_BALL = 39;
    const SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL = 40;
    const WEIGHTED_SINGLE_LEG_HIP_RAISE_WITH_HEAD_ON_BOSU_BALL = 41;
    const WEIGHTED_CLAM_BRIDGE = 42;
    const SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL = 43;
    const CLAMS = 44;
    const INNER_THIGH_CIRCLES = 45;
    const INNER_THIGH_SIDE_LIFT = 46;
    const LEG_CIRCLES = 47;
    const LEG_LIFT = 48;
    const LEG_LIFT_IN_EXTERNAL_ROTATION = 49;
}
