<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * Profile Version = 21.60Release
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * LungeExerciseName constants
 */
final class LungeExerciseName
{
    const OVERHEAD_LUNGE = 0;
    const LUNGE_MATRIX = 1;
    const WEIGHTED_LUNGE_MATRIX = 2;
    const ALTERNATING_BARBELL_FORWARD_LUNGE = 3;
    const ALTERNATING_DUMBBELL_LUNGE_WITH_REACH = 4;
    const BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT = 5;
    const BARBELL_BOX_LUNGE = 6;
    const BARBELL_BULGARIAN_SPLIT_SQUAT = 7;
    const BARBELL_CROSSOVER_LUNGE = 8;
    const BARBELL_FRONT_SPLIT_SQUAT = 9;
    const BARBELL_LUNGE = 10;
    const BARBELL_REVERSE_LUNGE = 11;
    const BARBELL_SIDE_LUNGE = 12;
    const BARBELL_SPLIT_SQUAT = 13;
    const CORE_CONTROL_REAR_LUNGE = 14;
    const DIAGONAL_LUNGE = 15;
    const DROP_LUNGE = 16;
    const DUMBBELL_BOX_LUNGE = 17;
    const DUMBBELL_BULGARIAN_SPLIT_SQUAT = 18;
    const DUMBBELL_CROSSOVER_LUNGE = 19;
    const DUMBBELL_DIAGONAL_LUNGE = 20;
    const DUMBBELL_LUNGE = 21;
    const DUMBBELL_LUNGE_AND_ROTATION = 22;
    const DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT = 23;
    const DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS = 24;
    const DUMBBELL_SIDE_LUNGE = 25;
    const ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT = 26;
    const FRONT_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT = 27;
    const GUNSLINGER_LUNGE = 28;
    const LAWNMOWER_LUNGE = 29;
    const LOW_LUNGE_WITH_ISOMETRIC_ADDUCTION = 30;
    const LOW_SIDE_TO_SIDE_LUNGE = 31;
    const LUNGE = 32;
    const WEIGHTED_LUNGE = 33;
    const LUNGE_WITH_ARM_REACH = 34;
    const LUNGE_WITH_DIAGONAL_REACH = 35;
    const LUNGE_WITH_SIDE_BEND = 36;
    const OFFSET_DUMBBELL_LUNGE = 37;
    const OFFSET_DUMBBELL_REVERSE_LUNGE = 38;
    const OVERHEAD_BULGARIAN_SPLIT_SQUAT = 39;
    const OVERHEAD_DUMBBELL_REVERSE_LUNGE = 40;
    const OVERHEAD_DUMBBELL_SPLIT_SQUAT = 41;
    const OVERHEAD_LUNGE_WITH_ROTATION = 42;
    const REVERSE_BARBELL_BOX_LUNGE = 43;
    const REVERSE_BOX_LUNGE = 44;
    const REVERSE_DUMBBELL_BOX_LUNGE = 45;
    const REVERSE_DUMBBELL_CROSSOVER_LUNGE = 46;
    const REVERSE_DUMBBELL_DIAGONAL_LUNGE = 47;
    const REVERSE_LUNGE_WITH_REACH_BACK = 48;
    const WEIGHTED_REVERSE_LUNGE_WITH_REACH_BACK = 49;
    const REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH = 50;
    const WEIGHTED_REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH = 51;
    const REVERSE_SLIDING_BOX_LUNGE = 52;
    const WEIGHTED_REVERSE_SLIDING_BOX_LUNGE = 53;
    const REVERSE_SLIDING_LUNGE = 54;
    const WEIGHTED_REVERSE_SLIDING_LUNGE = 55;
    const RUNNERS_LUNGE_TO_BALANCE = 56;
    const WEIGHTED_RUNNERS_LUNGE_TO_BALANCE = 57;
    const SHIFTING_SIDE_LUNGE = 58;
    const SIDE_AND_CROSSOVER_LUNGE = 59;
    const WEIGHTED_SIDE_AND_CROSSOVER_LUNGE = 60;
    const SIDE_LUNGE = 61;
    const WEIGHTED_SIDE_LUNGE = 62;
    const SIDE_LUNGE_AND_PRESS = 63;
    const SIDE_LUNGE_JUMP_OFF = 64;
    const SIDE_LUNGE_SWEEP = 65;
    const WEIGHTED_SIDE_LUNGE_SWEEP = 66;
    const SIDE_LUNGE_TO_CROSSOVER_TAP = 67;
    const WEIGHTED_SIDE_LUNGE_TO_CROSSOVER_TAP = 68;
    const SIDE_TO_SIDE_LUNGE_CHOPS = 69;
    const WEIGHTED_SIDE_TO_SIDE_LUNGE_CHOPS = 70;
    const SIFF_JUMP_LUNGE = 71;
    const WEIGHTED_SIFF_JUMP_LUNGE = 72;
    const SINGLE_ARM_REVERSE_LUNGE_AND_PRESS = 73;
    const SLIDING_LATERAL_LUNGE = 74;
    const WEIGHTED_SLIDING_LATERAL_LUNGE = 75;
    const WALKING_BARBELL_LUNGE = 76;
    const WALKING_DUMBBELL_LUNGE = 77;
    const WALKING_LUNGE = 78;
    const WEIGHTED_WALKING_LUNGE = 79;
    const WIDE_GRIP_OVERHEAD_BARBELL_SPLIT_SQUAT = 80;
}
