<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * Profile Version = 21.40Release
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * PlankExerciseName constants
 */
final class PlankExerciseName
{
    const _45_DEGREE_PLANK = 0;
    const WEIGHTED_45_DEGREE_PLANK = 1;
    const _90_DEGREE_STATIC_HOLD = 2;
    const WEIGHTED_90_DEGREE_STATIC_HOLD = 3;
    const BEAR_CRAWL = 4;
    const WEIGHTED_BEAR_CRAWL = 5;
    const CROSS_BODY_MOUNTAIN_CLIMBER = 6;
    const WEIGHTED_CROSS_BODY_MOUNTAIN_CLIMBER = 7;
    const ELBOW_PLANK_PIKE_JACKS = 8;
    const WEIGHTED_ELBOW_PLANK_PIKE_JACKS = 9;
    const ELEVATED_FEET_PLANK = 10;
    const WEIGHTED_ELEVATED_FEET_PLANK = 11;
    const ELEVATOR_ABS = 12;
    const WEIGHTED_ELEVATOR_ABS = 13;
    const EXTENDED_PLANK = 14;
    const WEIGHTED_EXTENDED_PLANK = 15;
    const FULL_PLANK_PASSE_TWIST = 16;
    const WEIGHTED_FULL_PLANK_PASSE_TWIST = 17;
    const INCHING_ELBOW_PLANK = 18;
    const WEIGHTED_INCHING_ELBOW_PLANK = 19;
    const INCHWORM_TO_SIDE_PLANK = 20;
    const WEIGHTED_INCHWORM_TO_SIDE_PLANK = 21;
    const KNEELING_PLANK = 22;
    const WEIGHTED_KNEELING_PLANK = 23;
    const KNEELING_SIDE_PLANK_WITH_LEG_LIFT = 24;
    const WEIGHTED_KNEELING_SIDE_PLANK_WITH_LEG_LIFT = 25;
    const LATERAL_ROLL = 26;
    const WEIGHTED_LATERAL_ROLL = 27;
    const LYING_REVERSE_PLANK = 28;
    const WEIGHTED_LYING_REVERSE_PLANK = 29;
    const MEDICINE_BALL_MOUNTAIN_CLIMBER = 30;
    const WEIGHTED_MEDICINE_BALL_MOUNTAIN_CLIMBER = 31;
    const MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION = 32;
    const WEIGHTED_MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION = 33;
    const MOUNTAIN_CLIMBER = 34;
    const WEIGHTED_MOUNTAIN_CLIMBER = 35;
    const MOUNTAIN_CLIMBER_ON_SLIDING_DISCS = 36;
    const WEIGHTED_MOUNTAIN_CLIMBER_ON_SLIDING_DISCS = 37;
    const MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL = 38;
    const WEIGHTED_MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL = 39;
    const MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH = 40;
    const MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL = 41;
    const WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL = 42;
    const PLANK = 43;
    const PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS = 44;
    const WEIGHTED_PLANK_JACKS_WITH_FEET_ON_SLIDING_DISCS = 45;
    const PLANK_KNEE_TWIST = 46;
    const WEIGHTED_PLANK_KNEE_TWIST = 47;
    const PLANK_PIKE_JUMPS = 48;
    const WEIGHTED_PLANK_PIKE_JUMPS = 49;
    const PLANK_PIKES = 50;
    const WEIGHTED_PLANK_PIKES = 51;
    const PLANK_TO_STAND_UP = 52;
    const WEIGHTED_PLANK_TO_STAND_UP = 53;
    const PLANK_WITH_ARM_RAISE = 54;
    const WEIGHTED_PLANK_WITH_ARM_RAISE = 55;
    const PLANK_WITH_KNEE_TO_ELBOW = 56;
    const WEIGHTED_PLANK_WITH_KNEE_TO_ELBOW = 57;
    const PLANK_WITH_OBLIQUE_CRUNCH = 58;
    const WEIGHTED_PLANK_WITH_OBLIQUE_CRUNCH = 59;
    const PLYOMETRIC_SIDE_PLANK = 60;
    const WEIGHTED_PLYOMETRIC_SIDE_PLANK = 61;
    const ROLLING_SIDE_PLANK = 62;
    const WEIGHTED_ROLLING_SIDE_PLANK = 63;
    const SIDE_KICK_PLANK = 64;
    const WEIGHTED_SIDE_KICK_PLANK = 65;
    const SIDE_PLANK = 66;
    const WEIGHTED_SIDE_PLANK = 67;
    const SIDE_PLANK_AND_ROW = 68;
    const WEIGHTED_SIDE_PLANK_AND_ROW = 69;
    const SIDE_PLANK_LIFT = 70;
    const WEIGHTED_SIDE_PLANK_LIFT = 71;
    const SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL = 72;
    const WEIGHTED_SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL = 73;
    const SIDE_PLANK_WITH_FEET_ON_BENCH = 74;
    const WEIGHTED_SIDE_PLANK_WITH_FEET_ON_BENCH = 75;
    const SIDE_PLANK_WITH_KNEE_CIRCLE = 76;
    const WEIGHTED_SIDE_PLANK_WITH_KNEE_CIRCLE = 77;
    const SIDE_PLANK_WITH_KNEE_TUCK = 78;
    const WEIGHTED_SIDE_PLANK_WITH_KNEE_TUCK = 79;
    const SIDE_PLANK_WITH_LEG_LIFT = 80;
    const WEIGHTED_SIDE_PLANK_WITH_LEG_LIFT = 81;
    const SIDE_PLANK_WITH_REACH_UNDER = 82;
    const WEIGHTED_SIDE_PLANK_WITH_REACH_UNDER = 83;
    const SINGLE_LEG_ELEVATED_FEET_PLANK = 84;
    const WEIGHTED_SINGLE_LEG_ELEVATED_FEET_PLANK = 85;
    const SINGLE_LEG_FLEX_AND_EXTEND = 86;
    const WEIGHTED_SINGLE_LEG_FLEX_AND_EXTEND = 87;
    const SINGLE_LEG_SIDE_PLANK = 88;
    const WEIGHTED_SINGLE_LEG_SIDE_PLANK = 89;
    const SPIDERMAN_PLANK = 90;
    const WEIGHTED_SPIDERMAN_PLANK = 91;
    const STRAIGHT_ARM_PLANK = 92;
    const WEIGHTED_STRAIGHT_ARM_PLANK = 93;
    const STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH = 94;
    const WEIGHTED_STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH = 95;
    const SWISS_BALL_PLANK = 96;
    const WEIGHTED_SWISS_BALL_PLANK = 97;
    const SWISS_BALL_PLANK_LEG_LIFT = 98;
    const WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT = 99;
    const SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD = 100;
    const SWISS_BALL_PLANK_WITH_FEET_ON_BENCH = 101;
    const WEIGHTED_SWISS_BALL_PLANK_WITH_FEET_ON_BENCH = 102;
    const SWISS_BALL_PRONE_JACKKNIFE = 103;
    const WEIGHTED_SWISS_BALL_PRONE_JACKKNIFE = 104;
    const SWISS_BALL_SIDE_PLANK = 105;
    const WEIGHTED_SWISS_BALL_SIDE_PLANK = 106;
    const THREE_WAY_PLANK = 107;
    const WEIGHTED_THREE_WAY_PLANK = 108;
    const TOWEL_PLANK_AND_KNEE_IN = 109;
    const WEIGHTED_TOWEL_PLANK_AND_KNEE_IN = 110;
    const T_STABILIZATION = 111;
    const WEIGHTED_T_STABILIZATION = 112;
    const TURKISH_GET_UP_TO_SIDE_PLANK = 113;
    const WEIGHTED_TURKISH_GET_UP_TO_SIDE_PLANK = 114;
    const TWO_POINT_PLANK = 115;
    const WEIGHTED_TWO_POINT_PLANK = 116;
    const WEIGHTED_PLANK = 117;
    const WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT = 118;
    const WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT = 119;
    const WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT = 120;
    const WEIGHTED_WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT = 121;
    const WIDE_STANCE_PLANK_WITH_LEG_LIFT = 122;
    const WEIGHTED_WIDE_STANCE_PLANK_WITH_LEG_LIFT = 123;
    const WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT = 124;
    const WEIGHTED_MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH = 125;
    const WEIGHTED_SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD = 126;
    const WEIGHTED_WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT = 127;
    const PLANK_WITH_FEET_ON_SWISS_BALL = 128;
    const SIDE_PLANK_TO_PLANK_WITH_REACH_UNDER = 129;
    const BRIDGE_WITH_GLUTE_LOWER_LIFT = 130;
    const BRIDGE_ONE_LEG_BRIDGE = 131;
    const PLANK_WITH_ARM_VARIATIONS = 132;
    const PLANK_WITH_LEG_LIFT = 133;
    const REVERSE_PLANK_WITH_LEG_PULL = 134;
}
