<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * Profile Version = 21.54Release
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * PushUpExerciseName constants
 */
final class PushUpExerciseName
{
    const CHEST_PRESS_WITH_BAND = 0;
    const ALTERNATING_STAGGERED_PUSH_UP = 1;
    const WEIGHTED_ALTERNATING_STAGGERED_PUSH_UP = 2;
    const ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP = 3;
    const WEIGHTED_ALTERNATING_HANDS_MEDICINE_BALL_PUSH_UP = 4;
    const BOSU_BALL_PUSH_UP = 5;
    const WEIGHTED_BOSU_BALL_PUSH_UP = 6;
    const CLAPPING_PUSH_UP = 7;
    const WEIGHTED_CLAPPING_PUSH_UP = 8;
    const CLOSE_GRIP_MEDICINE_BALL_PUSH_UP = 9;
    const WEIGHTED_CLOSE_GRIP_MEDICINE_BALL_PUSH_UP = 10;
    const CLOSE_HANDS_PUSH_UP = 11;
    const WEIGHTED_CLOSE_HANDS_PUSH_UP = 12;
    const DECLINE_PUSH_UP = 13;
    const WEIGHTED_DECLINE_PUSH_UP = 14;
    const DIAMOND_PUSH_UP = 15;
    const WEIGHTED_DIAMOND_PUSH_UP = 16;
    const EXPLOSIVE_CROSSOVER_PUSH_UP = 17;
    const WEIGHTED_EXPLOSIVE_CROSSOVER_PUSH_UP = 18;
    const EXPLOSIVE_PUSH_UP = 19;
    const WEIGHTED_EXPLOSIVE_PUSH_UP = 20;
    const FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP = 21;
    const WEIGHTED_FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP = 22;
    const HAND_RELEASE_PUSH_UP = 23;
    const WEIGHTED_HAND_RELEASE_PUSH_UP = 24;
    const HANDSTAND_PUSH_UP = 25;
    const WEIGHTED_HANDSTAND_PUSH_UP = 26;
    const INCLINE_PUSH_UP = 27;
    const WEIGHTED_INCLINE_PUSH_UP = 28;
    const ISOMETRIC_EXPLOSIVE_PUSH_UP = 29;
    const WEIGHTED_ISOMETRIC_EXPLOSIVE_PUSH_UP = 30;
    const JUDO_PUSH_UP = 31;
    const WEIGHTED_JUDO_PUSH_UP = 32;
    const KNEELING_PUSH_UP = 33;
    const WEIGHTED_KNEELING_PUSH_UP = 34;
    const MEDICINE_BALL_CHEST_PASS = 35;
    const MEDICINE_BALL_PUSH_UP = 36;
    const WEIGHTED_MEDICINE_BALL_PUSH_UP = 37;
    const ONE_ARM_PUSH_UP = 38;
    const WEIGHTED_ONE_ARM_PUSH_UP = 39;
    const WEIGHTED_PUSH_UP = 40;
    const PUSH_UP_AND_ROW = 41;
    const WEIGHTED_PUSH_UP_AND_ROW = 42;
    const PUSH_UP_PLUS = 43;
    const WEIGHTED_PUSH_UP_PLUS = 44;
    const PUSH_UP_WITH_FEET_ON_SWISS_BALL = 45;
    const WEIGHTED_PUSH_UP_WITH_FEET_ON_SWISS_BALL = 46;
    const PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL = 47;
    const WEIGHTED_PUSH_UP_WITH_ONE_HAND_ON_MEDICINE_BALL = 48;
    const SHOULDER_PUSH_UP = 49;
    const WEIGHTED_SHOULDER_PUSH_UP = 50;
    const SINGLE_ARM_MEDICINE_BALL_PUSH_UP = 51;
    const WEIGHTED_SINGLE_ARM_MEDICINE_BALL_PUSH_UP = 52;
    const SPIDERMAN_PUSH_UP = 53;
    const WEIGHTED_SPIDERMAN_PUSH_UP = 54;
    const STACKED_FEET_PUSH_UP = 55;
    const WEIGHTED_STACKED_FEET_PUSH_UP = 56;
    const STAGGERED_HANDS_PUSH_UP = 57;
    const WEIGHTED_STAGGERED_HANDS_PUSH_UP = 58;
    const SUSPENDED_PUSH_UP = 59;
    const WEIGHTED_SUSPENDED_PUSH_UP = 60;
    const SWISS_BALL_PUSH_UP = 61;
    const WEIGHTED_SWISS_BALL_PUSH_UP = 62;
    const SWISS_BALL_PUSH_UP_PLUS = 63;
    const WEIGHTED_SWISS_BALL_PUSH_UP_PLUS = 64;
    const T_PUSH_UP = 65;
    const WEIGHTED_T_PUSH_UP = 66;
    const TRIPLE_STOP_PUSH_UP = 67;
    const WEIGHTED_TRIPLE_STOP_PUSH_UP = 68;
    const WIDE_HANDS_PUSH_UP = 69;
    const WEIGHTED_WIDE_HANDS_PUSH_UP = 70;
    const PARALLETTE_HANDSTAND_PUSH_UP = 71;
    const WEIGHTED_PARALLETTE_HANDSTAND_PUSH_UP = 72;
    const RING_HANDSTAND_PUSH_UP = 73;
    const WEIGHTED_RING_HANDSTAND_PUSH_UP = 74;
    const RING_PUSH_UP = 75;
    const WEIGHTED_RING_PUSH_UP = 76;
    const PUSH_UP = 77;
    const PILATES_PUSHUP = 78;
}
