<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * Profile Version = 21.54Release
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * SquatExerciseName constants
 */
final class SquatExerciseName
{
    const LEG_PRESS = 0;
    const BACK_SQUAT_WITH_BODY_BAR = 1;
    const BACK_SQUATS = 2;
    const WEIGHTED_BACK_SQUATS = 3;
    const BALANCING_SQUAT = 4;
    const WEIGHTED_BALANCING_SQUAT = 5;
    const BARBELL_BACK_SQUAT = 6;
    const BARBELL_BOX_SQUAT = 7;
    const BARBELL_FRONT_SQUAT = 8;
    const BARBELL_HACK_SQUAT = 9;
    const BARBELL_HANG_SQUAT_SNATCH = 10;
    const BARBELL_LATERAL_STEP_UP = 11;
    const BARBELL_QUARTER_SQUAT = 12;
    const BARBELL_SIFF_SQUAT = 13;
    const BARBELL_SQUAT_SNATCH = 14;
    const BARBELL_SQUAT_WITH_HEELS_RAISED = 15;
    const BARBELL_STEPOVER = 16;
    const BARBELL_STEP_UP = 17;
    const BENCH_SQUAT_WITH_ROTATIONAL_CHOP = 18;
    const WEIGHTED_BENCH_SQUAT_WITH_ROTATIONAL_CHOP = 19;
    const BODY_WEIGHT_WALL_SQUAT = 20;
    const WEIGHTED_WALL_SQUAT = 21;
    const BOX_STEP_SQUAT = 22;
    const WEIGHTED_BOX_STEP_SQUAT = 23;
    const BRACED_SQUAT = 24;
    const CROSSED_ARM_BARBELL_FRONT_SQUAT = 25;
    const CROSSOVER_DUMBBELL_STEP_UP = 26;
    const DUMBBELL_FRONT_SQUAT = 27;
    const DUMBBELL_SPLIT_SQUAT = 28;
    const DUMBBELL_SQUAT = 29;
    const DUMBBELL_SQUAT_CLEAN = 30;
    const DUMBBELL_STEPOVER = 31;
    const DUMBBELL_STEP_UP = 32;
    const ELEVATED_SINGLE_LEG_SQUAT = 33;
    const WEIGHTED_ELEVATED_SINGLE_LEG_SQUAT = 34;
    const FIGURE_FOUR_SQUATS = 35;
    const WEIGHTED_FIGURE_FOUR_SQUATS = 36;
    const GOBLET_SQUAT = 37;
    const KETTLEBELL_SQUAT = 38;
    const KETTLEBELL_SWING_OVERHEAD = 39;
    const KETTLEBELL_SWING_WITH_FLIP_TO_SQUAT = 40;
    const LATERAL_DUMBBELL_STEP_UP = 41;
    const ONE_LEGGED_SQUAT = 42;
    const OVERHEAD_DUMBBELL_SQUAT = 43;
    const OVERHEAD_SQUAT = 44;
    const PARTIAL_SINGLE_LEG_SQUAT = 45;
    const WEIGHTED_PARTIAL_SINGLE_LEG_SQUAT = 46;
    const PISTOL_SQUAT = 47;
    const WEIGHTED_PISTOL_SQUAT = 48;
    const PLIE_SLIDES = 49;
    const WEIGHTED_PLIE_SLIDES = 50;
    const PLIE_SQUAT = 51;
    const WEIGHTED_PLIE_SQUAT = 52;
    const PRISONER_SQUAT = 53;
    const WEIGHTED_PRISONER_SQUAT = 54;
    const SINGLE_LEG_BENCH_GET_UP = 55;
    const WEIGHTED_SINGLE_LEG_BENCH_GET_UP = 56;
    const SINGLE_LEG_BENCH_SQUAT = 57;
    const WEIGHTED_SINGLE_LEG_BENCH_SQUAT = 58;
    const SINGLE_LEG_SQUAT_ON_SWISS_BALL = 59;
    const WEIGHTED_SINGLE_LEG_SQUAT_ON_SWISS_BALL = 60;
    const SQUAT = 61;
    const WEIGHTED_SQUAT = 62;
    const SQUATS_WITH_BAND = 63;
    const STAGGERED_SQUAT = 64;
    const WEIGHTED_STAGGERED_SQUAT = 65;
    const STEP_UP = 66;
    const WEIGHTED_STEP_UP = 67;
    const SUITCASE_SQUATS = 68;
    const SUMO_SQUAT = 69;
    const SUMO_SQUAT_SLIDE_IN = 70;
    const WEIGHTED_SUMO_SQUAT_SLIDE_IN = 71;
    const SUMO_SQUAT_TO_HIGH_PULL = 72;
    const SUMO_SQUAT_TO_STAND = 73;
    const WEIGHTED_SUMO_SQUAT_TO_STAND = 74;
    const SUMO_SQUAT_WITH_ROTATION = 75;
    const WEIGHTED_SUMO_SQUAT_WITH_ROTATION = 76;
    const SWISS_BALL_BODY_WEIGHT_WALL_SQUAT = 77;
    const WEIGHTED_SWISS_BALL_WALL_SQUAT = 78;
    const THRUSTERS = 79;
    const UNEVEN_SQUAT = 80;
    const WEIGHTED_UNEVEN_SQUAT = 81;
    const WAIST_SLIMMING_SQUAT = 82;
    const WALL_BALL = 83;
    const WIDE_STANCE_BARBELL_SQUAT = 84;
    const WIDE_STANCE_GOBLET_SQUAT = 85;
    const ZERCHER_SQUAT = 86;
    const KBS_OVERHEAD = 87;
    const SQUAT_AND_SIDE_KICK = 88;
    const SQUAT_JUMPS_IN_N_OUT = 89;
    const PILATES_PLIE_SQUATS_PARALLEL_TURNED_OUT_FLAT_AND_HEELS = 90;
    const RELEVE_STRAIGHT_LEG_AND_KNEE_BENT_WITH_ONE_LEG_VARIATION = 91;
}
