<?php

/**
 * FIT decoder
 *
 * @license MIT License
 *
 * ****WARNING****  This file is auto-generated! Do NOT edit.
 * Profile Version = 21.40Release
 */

declare(strict_types=1);

namespace Sportlog\FIT\Profile\Types;

/**
 * TricepsExtensionExerciseName constants
 */
final class TricepsExtensionExerciseName
{
    const BENCH_DIP = '0';
    const WEIGHTED_BENCH_DIP = '1';
    const BODY_WEIGHT_DIP = '2';
    const CABLE_KICKBACK = '3';
    const CABLE_LYING_TRICEPS_EXTENSION = '4';
    const CABLE_OVERHEAD_TRICEPS_EXTENSION = '5';
    const DUMBBELL_KICKBACK = '6';
    const DUMBBELL_LYING_TRICEPS_EXTENSION = '7';
    const EZ_BAR_OVERHEAD_TRICEPS_EXTENSION = '8';
    const INCLINE_DIP = '9';
    const WEIGHTED_INCLINE_DIP = '10';
    const INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION = '11';
    const LYING_DUMBBELL_PULLOVER_TO_EXTENSION = '12';
    const LYING_EZ_BAR_TRICEPS_EXTENSION = '13';
    const LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS = '14';
    const OVERHEAD_DUMBBELL_TRICEPS_EXTENSION = '15';
    const RECLINING_TRICEPS_PRESS = '16';
    const REVERSE_GRIP_PRESSDOWN = '17';
    const REVERSE_GRIP_TRICEPS_PRESSDOWN = '18';
    const ROPE_PRESSDOWN = '19';
    const SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION = '20';
    const SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION = '21';
    const SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION = '22';
    const SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION = '23';
    const SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION = '24';
    const SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION = '25';
    const SINGLE_LEG_BENCH_DIP_AND_KICK = '26';
    const WEIGHTED_SINGLE_LEG_BENCH_DIP_AND_KICK = '27';
    const SINGLE_LEG_DIP = '28';
    const WEIGHTED_SINGLE_LEG_DIP = '29';
    const STATIC_LYING_TRICEPS_EXTENSION = '30';
    const SUSPENDED_DIP = '31';
    const WEIGHTED_SUSPENDED_DIP = '32';
    const SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION = '33';
    const SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION = '34';
    const SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION = '35';
    const TABLETOP_DIP = '36';
    const WEIGHTED_TABLETOP_DIP = '37';
    const TRICEPS_EXTENSION_ON_FLOOR = '38';
    const TRICEPS_PRESSDOWN = '39';
    const WEIGHTED_DIP = '40';
}
